
shared:
  sample_rate: 4096
  noise_is_whitened: false
  band_low: 25.0
  band_high: 450.0
  bandpass_order: 4
  psd_floor: 1.0e-48
  psd_outband: 1.0e40


paths:
  data_dir: /path/to/train_test_hdf_dir
  noise_dir: /path/to/noise_dir
  checkpoint_dir: /path/to/checkpoints_dir

download:
  window_len_s: 4096
  min_window_len_s: 64.0

  train_noise:
    enabled: true
    gps_start: 1259193618
    gps_end: 1263081618
    n_segments: 100

    event_pad_s: 30.0
    glitch_sigma: 7.0
    glitch_max_frac: 0.001
    max_std_ratio: 20.0

    amp_thresh:
    rms_thresh:
    max_raw_std:
    min_raw_std:

  test:
    gps_start: 1264204818
    gps_end: 1267056018

    noise:
      enabled: false
      n_segments:

    signal:
      enabled: false
      n_events:

  plot_timeline: true
  plot_timeseries: true
  plot_psd: true
  target_plot_fs: 1024.0
  psd_seglen_s: 4.0
  

model:
  name: model_tcn_earlyfusion
  kwargs: {}
  
  
training:
  train_file: train_500.hdf
  val_file: test_500.hdf
  batch_size: 32
  num_workers: 8
  lr_init: 0.001
  max_epochs: 75

  dim: 1024
  segment_length: 4096
  edge_buffer: 2048
  whitening_context_seconds: 8.0
  noise_prob: 0.65
  normalize_per_window_shared: true

  p_higher_init: 0.90
  p_higher_fin: 0.25
  snr_range_high: [7.0, 13.0]
  snr_range_low: [2.0, 7.0]
