# AttenGW example configuration
# This file is used by both submit_download.slurm and submit.slurm.

shared:
  random_seed: 67
  sample_rate: 4096
  noise_is_whitened: false

  # Change if you know noise psd properties.
  band_low: 25.0
  band_high: 450.0
  bandpass_order: 4
  psd_floor: 1.0e-48
  psd_outband: 1.0e40


paths:
  # Edit these for your system.

  # data_dir should contain the injection files listed under training.train_file
  # and training.val_file. Each file should have:
  #
  #   /data/H1_wave   shape: (N, waveform_length)
  #   /data/L1_wave   shape: (N, waveform_length)
  #
  # noise_dir should contain downloaded noise files with:
  #
  #   /strain_H1
  #   /strain_L1
  #   /psd_H1
  #   /psd_L1
  #   /freqs
  # The downloader creates this with the correct structure automatically
  
  data_dir: /path/to/train_test_hdf_dir
  noise_dir: /path/to/noise_dir
  checkpoint_dir: /path/to/checkpoints_dir


download:
  window_len_s: 4096
  min_window_len_s: 64.0

  train_noise:
    enabled: true
    gps_start: 1263081618
    gps_end: 1264291218
    n_segments: 32

    event_pad_s: 30.0
    glitch_sigma: 7.0
    glitch_max_frac: 0.001
    max_std_ratio: 20.0

    amp_thresh:
    rms_thresh:
    max_raw_std:
    min_raw_std:

  test:
    gps_start: 1264291218
    gps_end: 1267056018

    noise:
      enabled: true
      n_segments:

    signal:
      enabled: true
      n_events:

  plot_timeline: true
  plot_timeseries: true
  plot_psd: true
  target_plot_fs: 1024.0
  psd_seglen_s: 4.0


model:
# Available models:
#   model_hdcn_crossattn
#   model_hdcn_graph
#   model_tcn_earlyfusion
#   model_tcn_sepstems_simplefusion
#   model_tcn_sepstems_interaction
#   model_tcn_temporalattn_gated
#   model_tcn_stft
#   model_bimamba
  name: model_tcn_earlyfusion
  kwargs: {}

training:
  # Commonly changed.
  train_file: train.hdf
  val_file: val.hdf
  batch_size: 32
  num_workers: 4
  lr_init: 0.001
  max_epochs: 100

  # Data/label settings.
  dim: 1024
  segment_length: 4096
  edge_buffer: 2048
  whitening_context_seconds: 8.0
  noise_prob: 0.60
  normalize_per_window_shared: true

  # Advanced curriculum settings; usually leave unchanged.
  p_higher_init: 0.90
  p_higher_fin: 0.25
  snr_range_high: [10.0, 25.0]
  snr_range_low: [7.0, 15.0]
